// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"dashboard\"><div class=\"card\"><h3>Top Archetypes</h3><ul class=\"archetype-list\"><li><span class=\"archetype-name\">Arishem</span><div class=\"archetype-stats\"><span class=\"stat\">32%</span></div></li></ul></div><div class=\"card\"><h3>Tournament Stats</h3><div style=\"margin-top: 20px;\"><div style=\"margin-bottom: 15px;\"><strong>Total Decks:</strong> 1024</div><div style=\"margin-bottom: 15px;\"><strong>Unique Archetypes:</strong> XX</div><div style=\"margin-bottom: 15px;\"><strong>Most Used Card:</strong> Shang-Chi (89% of decks)</div></div></div><div class=\"card deck-analysis\"><h3>Card Usage Analysis</h3><div class=\"card-grid\"><div class=\"card-item\"><div class=\"card-name\">Shang-Chi</div><div class=\"card-usage\">89%</div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
